# Generated by Django 2.2.1 on 2019-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='0', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True, verbose_name='作者年龄'),
        ),
    ]
